### PR TITLE
Update .clang-format

### PR DESCRIPTION
**Pull request by blhough**
You get 2 vetoes 😛

### CODE REVIEW

**Comment by ids1024** [comment]
I personally don't really like breaking before braces and spaces in parentheses.  But of course, it doesn't really matter much.

**Comment by blhough** [comment]
Do you think now would be a good time to format all the files?

**Comment by ids1024** [comment]
It's probably as good a time as any. But if everyone isn't running clang-format themselves (such as with the plugin) it won't be easy to maintain style.

Travis could probably check style, but that shouldn't be added until everyone is formatting their code.

**Comment by blhough** [comment]
#31 That's what this if for

**Pull request merged**
